FORMAT: 1A
HOST: http://digitalnsk.sibtiger.com:5000/

# DigitalNSK

    Описание

## Пользователь [/user]

### Авторизация пользователя [POST/user/signin/]
##### с помощью email'а и пароля
+ Request (application/json)

    + Body

            {
                "email": "Электронный_адрес",
                "password": "Пароль"
            }

+ Response 201 (application/json)

    + Headers
            jwt: "bearer token"

    + Body

            {
                "data":
                {
                    "email": "Электронный_адрес",
                    "firstName": "Имя",
                    "lastName": "Фамилия"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {
                    "error": "Пользователь не найден"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "errors":
                {
                    "error": "Пожалуйста, введите email и пароль"
                }
            }

### Регистрация пользователя(Участник) [POST/user/signup/]
##### с помощью email'а и пароля
+ Request (application/json)

    + Body
            {
                "id":
                {
                    "email": "Электронный_адрес*",
                    "firstName": "Имя*",
                    "lastName": "Фамилия*",
                    "patronymic": "Отчество",
                    "password": "Пароль*",
                    "photo": "Фотграфия",
                    "phoneNumber": "Номер_телефона*",
                    "role": "Роль*"
                }
                "eduInstitution": "Учебное_заведение",
                "level": "Класс/курс",
                "vkURL": "Ссылка_на_аккаунт_Вконтакте",
                "instURL": "Ссылка_на_аккаунт_instagram",
                "fbURL": "Ссылка_на_аккаунт_facebook",
                "mailing": "Подписка_на_рассылку"
            }

+ Response 201 (application/json)

    + Headers
            jwt: bearer token

    + Body
            {
                "data": 
                {
                    "id": 
                    {
                        "id": "id пользователя",
                        "email": "email",
                        "date_joined": "дата регистрации",
                        "firstName": "имя",
                        "lastName": "фамилия",
                        "photo": "url фото",
                        "patronymic": "отчество",
                        "role": "роль"
                    },
                    "eduInstitution": "образовательное учреждение",
                    "level": "класс/курс",
                    "vkURL": "vk url",
                    "instURL": "instagram url",
                    "fbURL": "fb url",
                    "passedTests": ["завершенные тесты"],
                    "events": "мероприятия || null",
                    "progress": "личный прогресс"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {
                    "error": "Не удалось зарегистрировать пользователя"
                }
            }

### Редактирование профиля [POST/user/edit/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Восстановление пароля [POST/user/recovery-password/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Авторизация через Вконтакте [POST/user/auth-vk/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Авторизация через Instagram [POST/user/auth-inst/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Авторизация через Facebook [POST/user/auth-fb/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Регистрация через Вконтакте [POST/user/reg-vk/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Регистрация через Instagram [POST/user/reg-inst/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Регистрация через Facebook [POST/user/reg-fb/]
##### не готово!!!
+ Request (application/json)

    + Body
            {

            }

+ Response 201 (application/json)

    + Body
            {
                "data":
                {

                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }
