FORMAT: 1A
HOST: http://digitalnsk.sibtiger.com:5000/

# DigitalNSK
    Описание

## Пользователь [/user]

### Авторизация пользователя [POST/user/signin/]
##### с помощью email'а и пароля
+ Request (application/json)

    + Body

            {
                "email": "Электронный_адрес",
                "password": "Пароль"
            }

+ Response 201 (application/json)

    + Headers
            jwt: "bearer token"

    + Body

            {
                "data":
                {
                    "email": "Электронный_адрес",
                    "firstName": "Имя",
                    "lastName": "Фамилия"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {
                    "error": "Пользователь не найден"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "errors":
                {
                    "error": "Пожалуйста, введите email и пароль"
                }
            }

### Регистрация пользователя(Участник) [POST/user/signup/]
##### с помощью email'а и пароля
+ Request (application/json)

    + Body
            {
                "id":
                {
                    "email": "Электронный_адрес*",
                    "firstName": "Имя*",
                    "lastName": "Фамилия*",
                    "patronymic": "Отчество",
                    "password": "Пароль*",
                    "photo": "Фотграфия",
                    "phoneNumber": "Номер_телефона*",
                    "role": "Роль*"
                },
                "eduInstitution": { "name": "Учебное_заведение"},
                "level": "Класс/курс",
                "vkURL": "Ссылка_на_аккаунт_Вконтакте",
                "instURL": "Ссылка_на_аккаунт_instagram",
                "fbURL": "Ссылка_на_аккаунт_facebook",
                "mailing": "Подписка_на_рассылку"
            }

+ Response 201 (application/json)

    + Body
            {
                "data": 
                {
                    "id": 
                    {
                        "id": "id пользователя",
                        "email": "email",
                        "date_joined": "дата регистрации",
                        "firstName": "имя",
                        "lastName": "фамилия",
                        "photo": "url фото",
                        "patronymic": "отчество",
                        "role": "роль"
                    },
                    "eduInstitution": "образовательное учреждение",
                    "level": "класс/курс",
                    "vkURL": "vk url",
                    "instURL": "instagram url",
                    "fbURL": "fb url",
                    "passedTests": ["завершенные тесты"],
                    "events": "мероприятия || null",
                    "progress": "личный прогресс"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {
                    "error": "Не удалось зарегистрировать пользователя"
                }
            }

### Редактирование профиля [PUT/user/edit/]
+ Request (application/json)

    + Body
            {
                "id":
                {
                    "firstName": "Имя",
                    "lastName": "Фамилия",
                    "email": "email",
                    "patronymic": "Отчество",
                    "phoneNumber": "Номер телефона",
                    "password": "новый пароль",
                }, 
                "otherFields1": "поле зависит от роли",
                "otherFields2": "поле зависит от роли",
                "otherFieldsN": "поле зависит от роли"
            }

+ Response 200 (application/json)

    + Body
           {
                "data": 
                {
                    "id": 
                    {
                        "id": "id пользователя",
                        "email": "email",
                        "date_joined": "дата регистрации",
                        "firstName": "имя",
                        "lastName": "фамилия",
                        "photo": "url фото",
                        "patronymic": "отчество",
                        "role": "роль"
                    },
                    "поля зав-ие от роли": "их может быть несколько",
                    "jwt": "токен"
                }
            }

+ Response 403 (application/json)

    + Body

            {
                "errors":
                {

                }
            }

### Восстановление пароля [POST/user/recovery-password/]
+ Request (application/json)

    + Body
            {
                "email": "email пользователя"
            }

+ Response 200 (application/json)

    + Body
            {
                "data": null
            }

+ Response 400 (application/json)

    + Body

            {
                "errors": {
                    "error": "Неизвестный параметр"
                }
            }
+ Response 400 (application/json)

    + Body

            {
                "errors": {
                    "error": "id не указан"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "errors": {
                    "error": "Неизвестная ошибка"
                }
            }

### Восстановление пароля [DELETE/user/recovery-password/]
+ Request (application/json)

    + Body
            {
                "hash": "hash из параметра, после перехода с почты"
            }

+ Response 200 (application/json)

    + Body
            {
                "data": null
            }

+ Response 400 (application/json)

    + Body

            {
                "errors": {
                    "error": "Неизвестная ошибка"
                }
            }

+ Response 400 (application/json)

    + Body

            {
                "errors": {
                    "error": "Данной ссылки не найдено"
                }
            }

## Тестирование [/tests]

### Получение теста[GET/tests?{type}]
+ Parameters
        + type (number) - Номер теста
+ Request
    + Headers
            id: Идентификатор пользователя
+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "id": "Идентификатор теста",
                    "description": "Описание теста",
                    "questions": [
                        {
                            "id": "Идентификатор вопроса",
                            "content": "Сам вопрос",
                            "answers": [{"id": "Идентификатор ответа", "content": "Сам ответ", "group": "Идентификатор группы"}]
                        }
                    ]
                }
            }

+ Response 403 (application/json)
    + Body
            {
                "error": "что-то пошло не так"
            }

### Получение результата теста №1 [POST/tests/]
+ Request (application/json)
    + Headers
            id: Идентификатор пользователя
    + Body
            {
                "type": 1
                "answers": [массив int (от 1 до 5) - идентификатор группы ответа] 
            }

+ Response 200 (application/json)

    + Body
            {
                "data": {
                    "values": [массив int - идентификаторы групп ответов],
                    "types": [массив str - название групп ответов]
                }
            }

+ Response 403 (application/json)
    + Body
            {
                "error": текст ошибки
            }
            
### Получение результата теста №2 [POST/tests/]
##### Для получения результатов с дополнительным вопросом нужно отправить два запроса(один до доплнительного вопроса, другой после - в массив ответов добавляется ответ на допю вопрос)
+ Request (application/json)
    + Headers
            id Идентификатор пользователя
    + Body
            {
                "type": 2
                "answers": [массив int (от 1 до 5) - идентификатор группы ответа] 
            }

+ Response 200 (application/json)

    + Body
            {
                "data": {
                    "values": [массив int - идентификаторы групп ответов],
                    "types": [массив str - название групп ответов]
                    "additional": false - если не нужен доп. вопрос/true - если нужен доп. вопрос
                    Если "additional": true, то 
                        "description": описание дополнительного вопроса,
                        "questions": [{"types": "Сам ответ", "group": "Идентификатор группы"}]
                }
            }

+ Response 403 (application/json)
    + Body
            {
                "error": текст ошибки
            }

### Получение результата теста №3 [POST/tests/]
+ Request (application/json)
    + Headers
            id Идентификатор пользователя
    + Body
            {
                "type": 3
                "id": Идентификатор теста
                "answers": [массив int (от 1 до 5) - идентификатор группы ответа] 
            }

+ Response 200 (application/json)
    + Body
            {
                "result": оценка по 10-ти балльной шкале
            }

+ Response 403 (application/json)
    + Body
            {
                "error": текст ошибки
            }

## Пространство проб [/event]


### Получение списка мероприятий [GET/event?{date}]
##### По кометенции + дате проведения
+ Parameters
        + date (string) - Дата в формате DD.MM.YYYY
+ Request (application/json)
    + Headers
            id Идентификатор пользователя

+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "list": [
                        {
                            "id": Идентификатор мероприятия,
                            "name": "Название",
                            "img": "Ссылка на изображение",
                            "date": "Дата в формате DD.MM.YYYY",
                            "time": "Время в формате HH:MM",
                            "description": "Описание",
                            "mainCompetence": [ массив основных компетенций
                                {
                                    "id": "Идентификатор компетенции,
                                    "name": "Название компетенции"
                                }
                            ],
                            "competence": [ массив компетенций
                                {
                                    "id": "Идентификатор компетенции,
                                    "name": "Название компетенции"
                                }
                            ],
                            "points": [ массив выходных компетенций
                                {
                                    "id": Идентификатор  входных компетенций,
                                    "value": Баллы за входные кометенции,
                                    "competence": {
                                        "id": "Идентификатор компетенции,
                                        "name": "Название компетенции"
                                    }
                                },
                            ],
                            "venue": "Место проведения",
                            "format_event": "Формат мероприятия",
                            "max_partiсipants": "Максимальное количество участников",
                            "partiсipants": "Количество участников",
                            "partner": "Партнер",
                            "manager_name": "Имя организатора",
                            "manager_position": "Должность организатора",
                            "phonenumber": "Телефон организатора"
                        }
                    ]
                }
            }

+ Response 403 (application/json)
    + Body
            {
                "error": текст ошибки
            }

### Регистрация на мероприятии[POST/event/signup/]
+ Request (application/json)
    + Headers
            id Идентификатор пользователя
    + Body
            {
                "event": Идентификатор мароприятия
            }

+ Response 200 (application/json)
    + Body
            {
                "data": null
            }

+ Response 400 (application/json)
    + Body
            {
                "error": текст ошибки
            }
### Получение списка мероприятий[GET/event/signup/]
##### на которые пользователь загестрирован
+ Request (application/json)
    + Headers
            id Идентификатор пользователя

+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "list": [
                        {
                            "id": Идентификатор мероприятия,
                            "name": "Название",
                            "img": "Ссылка на изображение",
                            "date": "Дата в формате DD.MM.YYYY",
                            "time": "Время в формате HH:MM",
                            "description": "Описание",
                            "mainCompetence": [ массив основных компетенций
                                {
                                    "id": "Идентификатор компетенции,
                                    "name": "Название компетенции"
                                }
                            ],
                            "competence": [ массив компетенций
                                {
                                    "id": "Идентификатор компетенции,
                                    "name": "Название компетенции"
                                }
                            ],
                            "points": [ массив выходных компетенций
                                {
                                    "id": Идентификатор  входных компетенций,
                                    "value": Баллы за входные кометенции,
                                    "competence": {
                                        "id": "Идентификатор компетенции,
                                        "name": "Название компетенции"
                                    }
                                },
                            ],
                            "venue": "Место проведения",
                            "format_event": "Формат мероприятия",
                            "max_partiсipants": "Максимальное количество участников",
                            "partiсipants": "Количество участников",
                            "partner": "Партнер",
                            "manager_name": "Имя организатора",
                            "manager_position": "Должность организатора",
                            "phonenumber": "Телефон организатора"
                        }
                    ]
                }
            }

+ Response 400 (application/json)
    + Body
            {
                "error": текст ошибки
            }
### Получение информации о мероприятии[POST/event/event/]
+ Request (application/json)
    + Headers
            id Идентификатор пользователя
    + Body
            {
                "event": Идентификатор мароприятия
            }

+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "id": Идентификатор мероприятия,
                    "name": "Название",
                    "img": "Ссылка на изображение",
                    "date": "Дата в формате DD.MM.YYYY",
                    "time": "Время в формате HH:MM",
                    "description": "Описание",
                    "mainCompetence": [ массив основных компетенций
                        {
                            "id": "Идентификатор компетенции,
                            "name": "Название компетенции"
                        }
                    ],
                    "competence": [ массив компетенций
                        {
                            "id": "Идентификатор компетенции,
                            "name": "Название компетенции"
                        }
                    ],
                    "points": [ массив выходных компетенций
                        {
                            "id": Идентификатор  входных компетенций,
                            "value": Баллы за входные кометенции,
                            "competence": {
                                "id": "Идентификатор компетенции,
                                "name": "Название компетенции"
                            }
                        },
                    ],
                    "venue": "Место проведения",
                    "format_event": "Формат мероприятия",
                    "max_partiсipants": "Максимальное количество участников",
                    "partiсipants": "Количество участников",
                    "partner": "Партнер",
                    "manager_name": "Имя организатора",
                    "manager_position": "Должность организатора",
                    "phonenumber": "Телефон организатора"
                }
            }

+ Response 400 (application/json)
    + Body
            {
                "error": текст ошибки
            }