# Generated by Django 2.1.7 on 2019-05-13 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190430_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 13), verbose_name='Дата публикации'),
        ),
    ]
