# Generated by Django 2.1.7 on 2019-05-14 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190513_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 14), verbose_name='Дата публикации'),
        ),
    ]
