# Generated by Django 2.1.7 on 2019-05-16 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190514_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 16), verbose_name='Дата публикации'),
        ),
    ]
