# Generated by Django 2.1.7 on 2019-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190516_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=None, null=True, verbose_name='Дата публикации'),
        ),
    ]
