# Generated by Django 2.1.7 on 2019-03-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20190310_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='desciption',
            new_name='description',
        ),
    ]
