# Generated by Django 2.1.7 on 2019-03-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20190319_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='question', to='testing.Answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='test', to='testing.Answer', verbose_name='Вопросы'),
        ),
    ]
