# Generated by Django 2.1.7 on 2019-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20190319_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='mode',
            field=models.IntegerField(unique=True, verbose_name='Тип теста'),
        ),
    ]
