# Generated by Django 2.1.7 on 2019-03-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20190321_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='mode',
            field=models.IntegerField(verbose_name='Тип теста'),
        ),
    ]
