# Generated by Django 2.1.7 on 2019-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_auto_20190321_2306'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='competence',
        ),
        migrations.AddField(
            model_name='event',
            name='competence',
            field=models.ManyToManyField(related_name='event', to='testing.Group', verbose_name='Компетенция'),
        ),
    ]
