# Generated by Django 2.1.7 on 2019-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190328_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='competence',
        ),
        migrations.AddField(
            model_name='event',
            name='competence',
            field=models.CharField(blank=True, max_length=50, verbose_name='Компетенция'),
        ),
    ]
