# Generated by Django 2.1.7 on 2019-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190328_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_event',
            field=models.CharField(blank=True, max_length=50, verbose_name='Формат мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_task',
            field=models.CharField(blank=True, max_length=50, verbose_name='Формат задания'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Компетенция'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_partiсipant',
            field=models.IntegerField(default=0, verbose_name='Максимальное количестьво учатников'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.TextField(null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
