# Generated by Django 2.1.7 on 2019-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190328_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Копметенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Этап мероприятия',
                'verbose_name_plural': 'Этапы мероприятия',
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='max_partiсipant',
            new_name='max_partiсipants',
        ),
        migrations.AddField(
            model_name='event',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Вес мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='manager_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='partiсipants',
            field=models.IntegerField(default=0, verbose_name='Количестьво учатников'),
        ),
        migrations.AddField(
            model_name='event',
            name='partner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='event',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='competence',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=10, null=True, verbose_name='Дата проведения'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=5, null=True, verbose_name='Время проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='inherent_competence',
            field=models.ManyToManyField(related_name='event_add', to='event.Competence', verbose_name='Компетенция'),
        ),
        migrations.AddField(
            model_name='event',
            name='competence',
            field=models.ManyToManyField(related_name='event', to='event.Competence', verbose_name='Компетенция'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.ManyToManyField(blank=True, related_name='event', to='event.EventStage', verbose_name='Описание'),
        ),
    ]
