# Generated by Django 2.1.7 on 2019-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190329_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='competence',
            field=models.ManyToManyField(related_name='event', to='event.Competence', verbose_name='Компетенция(до)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='inherent_competence',
            field=models.ManyToManyField(related_name='event_add', to='event.Competence', verbose_name='Компетенция(после)'),
        ),
    ]
