# Generated by Django 2.1.7 on 2019-04-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190329_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Кол-во баллов')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='event.Competence', verbose_name='Компетенция')),
            ],
            options={
                'verbose_name': 'Балл за участие в мероприятии',
                'verbose_name_plural': 'Баллы за участие в мероприятии',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='inherent_competence',
        ),
        migrations.AlterField(
            model_name='event',
            name='competence',
            field=models.ManyToManyField(related_name='event', to='event.Competence', verbose_name='Полезно знать до мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.ManyToManyField(related_name='event_add', to='event.Point', verbose_name='Навыки, которые будем прокачивать'),
        ),
    ]
