# Generated by Django 2.1.7 on 2019-04-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20190410_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='competence',
            name='parent',
            field=models.IntegerField(blank=True, default=0, verbose_name='Родитель(id)'),
        ),
    ]
