# Generated by Django 2.1.7 on 2019-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20190414_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Базовая компетенция',
                'verbose_name_plural': 'Базовые компетенции',
            },
        ),
        migrations.CreateModel(
            name='MainCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Основная компетенция',
                'verbose_name_plural': 'Основные компетенции',
            },
        ),
        migrations.CreateModel(
            name='SideCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Субкомпетенция 3 уровня',
                'verbose_name_plural': 'Субкомпетенции 3 уровня',
            },
        ),
        migrations.CreateModel(
            name='SideCompetenceAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('subCompetence', models.ManyToManyField(related_name='sideCompAdd', to='event.SideCompetence', verbose_name='Субкомпетенции 3 уровня')),
            ],
            options={
                'verbose_name': 'Субкомпетенция 2 уровня',
                'verbose_name_plural': 'Субкомпетенции 2 уровня',
            },
        ),
        migrations.AddField(
            model_name='maincompetence',
            name='subCompetence',
            field=models.ManyToManyField(blank=True, related_name='mainComp', to='event.SideCompetenceAdd', verbose_name='Субкомпетенции 2 уровня'),
        ),
        migrations.AddField(
            model_name='basecompetence',
            name='subCompetence',
            field=models.ManyToManyField(related_name='baseComp', to='event.SideCompetenceAdd', verbose_name='Субкомпетенции 2 уровня'),
        ),
    ]
