# Generated by Django 2.1.7 on 2019-04-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190414_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventStage',
        ),
    ]
