# Generated by Django 2.1.7 on 2019-04-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_delete_eventstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='point',
            name='competence',
        ),
    ]
