# Generated by Django 2.1.7 on 2019-04-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20190414_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competence',
            field=models.ManyToManyField(blank=True, related_name='event', to='event.SideCompetence', verbose_name='Полезно знать до мероприятия'),
        ),
        migrations.AddField(
            model_name='point',
            name='competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='event.SideCompetence', verbose_name='Компетенция'),
        ),
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.ManyToManyField(blank=True, related_name='event_add', to='event.Point', verbose_name='Навыки, которые будем прокачивать'),
        ),
    ]
