# Generated by Django 2.1.7 on 2019-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20190414_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='MainCompetence',
            field=models.ManyToManyField(blank=True, related_name='event_m', to='event.MainCompetence', verbose_name='Основные компетенции'),
        ),
    ]
