# Generated by Django 2.1.7 on 2019-04-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_maincompetence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='MainCompetence',
            new_name='mainCompetence',
        ),
    ]
