# Generated by Django 2.1.7 on 2019-04-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20190415_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseCompetence',
        ),
        migrations.AddField(
            model_name='maincompetence',
            name='isBase',
            field=models.BooleanField(default=False, verbose_name='Базовая?'),
        ),
        migrations.AddField(
            model_name='sidecompetence',
            name='overCompetence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side', to='event.SideCompetenceAdd', verbose_name='Компетенция 2 уровня'),
        ),
        migrations.AddField(
            model_name='sidecompetenceadd',
            name='overCompetence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side', to='event.MainCompetence', verbose_name='Компетенция 1 уровня'),
        ),
    ]
