# Generated by Django 2.1.7 on 2019-04-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20190415_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mainComp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.MainCompetence', verbose_name='Основная компетенция'),
        ),
    ]
