# Generated by Django 2.1.7 on 2019-04-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_event_testimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
    ]
