# Generated by Django 2.1.7 on 2019-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20190419_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
