# Generated by Django 2.1.7 on 2019-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_auto_20190425_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активно?'),
        ),
    ]
