# Generated by Django 2.1.7 on 2019-02-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
            ],
            options={
                'verbose_name': 'Прогресс',
                'verbose_name_plural': 'Прогресс',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='', max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Email')),
                ('password', models.TextField(blank=True, default='', verbose_name='Пароль')),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=18)),
                ('role', models.CharField(choices=[('PATICIPANT', 'Участник'), ('TUTOR', 'Тьютор'), ('UNIVERSITY', 'Университет'), ('PARTNER', 'Партнер'), ('ADMINISTRATOR', 'Администратор')], default='PATICIPANT', max_length=20, verbose_name='Роль')),
                ('emailConfirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participant', serialize=False, to='user.User', verbose_name='Пользователь')),
                ('level', models.CharField(choices=[('8TH CLASS', '8 класс'), ('9TH CLASS', '9 класс'), ('10TH CLASS', '10 класс'), ('11TH CLASS', '11 класс'), ('1TH COURSE', '1 курс'), ('2TH COURSE', '2 курс'), ('3TH COURSE', '3 курс'), ('4TH COURSE', '4 курс'), ('5TH COURSE', '5 курс')], default='8TH CLASS', max_length=20, verbose_name='Класс/курс')),
                ('vkURL', models.URLField(blank=True, verbose_name='Ссылка на vkontakte')),
                ('instURL', models.URLField(blank=True, verbose_name='Ссылка на instagram')),
                ('fbURL', models.URLField(blank=True, verbose_name='Ссылка на facebook')),
                ('mailing', models.BooleanField(default=False)),
                ('eduInstitution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='institution.Institution', verbose_name='Образовательное учреждение')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='user.Progress', verbose_name='Мероприятия')),
                ('passedTests', models.ManyToManyField(related_name='participant', to='testing.Test', verbose_name='Завершенные тесты')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
