# Generated by Django 2.1.7 on 2019-02-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190227_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='eduInstitution',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='institution.Institution', verbose_name='Образовательное учреждение'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='events',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='user.Progress', verbose_name='Мероприятия'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.CharField(blank=True, choices=[('8TH CLASS', '8 класс'), ('9TH CLASS', '9 класс'), ('10TH CLASS', '10 класс'), ('11TH CLASS', '11 класс'), ('1TH COURSE', '1 курс'), ('2TH COURSE', '2 курс'), ('3TH COURSE', '3 курс'), ('4TH COURSE', '4 курс'), ('5TH COURSE', '5 курс')], default='8TH CLASS', max_length=20, verbose_name='Класс/курс'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='passedTests',
            field=models.ManyToManyField(blank=True, related_name='participant', to='testing.Test', verbose_name='Завершенные тесты'),
        ),
    ]
