# Generated by Django 2.1.7 on 2019-02-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190227_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='progress',
            field=models.FloatField(blank=True, default=0, verbose_name='Прогресс'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, verbose_name='Фото'),
        ),
    ]
