# Generated by Django 2.1.7 on 2019-02-27 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190227_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateJoined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Аккаунт действует'),
        ),
        migrations.AddField(
            model_name='user',
            name='isStaff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
    ]
