# Generated by Django 2.1.7 on 2019-02-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190227_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateJoined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isStaff',
            new_name='is_staff',
        ),
    ]
