# Generated by Django 2.1.7 on 2019-02-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190227_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARTICIPANT', 'Участник'), ('TUTOR', 'Тьютор'), ('UNIVERSITY', 'Университет'), ('PARTNER', 'Партнер'), ('ADMINISTRATOR', 'Администратор')], default='PARTICIPANT', max_length=20, verbose_name='Роль'),
        ),
    ]
