# Generated by Django 2.1.7 on 2019-02-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190228_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='eduInstitution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='institution.Institution', verbose_name='Образовательное учреждение'),
        ),
    ]
