# Generated by Django 2.1.7 on 2019-03-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190303_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='eduInstitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='institution.Institution', verbose_name='Образовательное учреждение'),
        ),
    ]
