# Generated by Django 2.1.7 on 2019-03-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190314_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.CharField(blank=True, choices=[('8 класс', '8 класс'), ('9 класс', '9 класс'), ('10 класс', '10 класс'), ('11 класс', '11 класс'), ('1 курс', '1 курс'), ('2 курс', '2 курс'), ('3 курс', '3 курс'), ('Сотрудник', 'Сотрудник'), ('Иное', 'Иное')], default='8 класс', max_length=20, verbose_name='Класс/курс'),
        ),
    ]
