# Generated by Django 2.1.7 on 2019-03-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190315_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='passedTests',
            field=models.ManyToManyField(blank=True, related_name='participant', to='testing.ResultOfTest', verbose_name='Результаты тестов'),
        ),
    ]
