# Generated by Django 2.1.7 on 2019-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190319_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='eduInstitution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Учебное учреждение'),
        ),
    ]
