# Generated by Django 2.1.7 on 2019-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20190325_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='competence',
            field=models.CharField(max_length=100, null=True, verbose_name='Компетенция'),
        ),
    ]
