# Generated by Django 2.1.7 on 2019-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_participant_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='competence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компетенция'),
        ),
    ]
