# Generated by Django 2.1.7 on 2019-03-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20190328_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='event.Competence', verbose_name='Компетенция'),
        ),
    ]
