# Generated by Django 2.1.7 on 2019-04-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190406_1321'),
        ('user', '0027_auto_20190329_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='event.Event', verbose_name='Мероприятие'),
        ),
    ]
