# Generated by Django 2.1.7 on 2019-04-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190411_0651'),
        ('user', '0027_auto_20190329_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='event.Event', verbose_name='Мероприятие'),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.AddField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participant', to='user.Progress', verbose_name='Мероприятия'),
        ),
    ]
