# Generated by Django 2.1.7 on 2019-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_progress_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.AddField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participant', to='user.Progress', verbose_name='Мероприятия'),
        ),
    ]
