# Generated by Django 2.1.7 on 2019-04-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20190414_1107'),
        ('user', '0029_auto_20190408_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='competence',
        ),
        migrations.AddField(
            model_name='participant',
            name='baseCompetences',
            field=models.ManyToManyField(blank=True, related_name='participant_b', to='event.Competence', verbose_name='Базовые компетенции'),
        ),
        migrations.AddField(
            model_name='participant',
            name='mainCompetence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_m', to='event.Competence', verbose_name='Основная компетенция'),
        ),
        migrations.AddField(
            model_name='participant',
            name='sideCompetences',
            field=models.ManyToManyField(blank=True, related_name='participant_s', to='event.Competence', verbose_name='Побочные компетенции'),
        ),
    ]
