# Generated by Django 2.1.7 on 2019-04-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20190414_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='mainCompetence',
            new_name='competence',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='baseCompetences',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='sideCompetences',
        ),
    ]
