# Generated by Django 2.1.7 on 2019-04-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190414_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='event.Competence', verbose_name='Основная компетенция'),
        ),
    ]
