# Generated by Django 2.1.7 on 2019-04-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20190414_1916'),
        ('user', '0032_auto_20190414_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='event',
        ),
        migrations.AddField(
            model_name='participant',
            name='mainCompetence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='event.MainCompetence', verbose_name='Основная компетенция'),
        ),
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы по основной компетенции'),
        ),
        migrations.AddField(
            model_name='participant',
            name='progressComp',
            field=models.ManyToManyField(blank=True, related_name='participant', to='user.Progress', verbose_name='Прогресс'),
        ),
        migrations.AddField(
            model_name='progress',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='event.SideCompetence', verbose_name='Компетенция'),
        ),
    ]
