# Generated by Django 2.1.7 on 2019-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_participant_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Фото'),
        ),
    ]
