# Generated by Django 2.1.7 on 2019-04-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20190419_1716'),
        ('user', '0035_auto_20190422_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_points', to='event.Event', verbose_name='Мероприятия')),
                ('points', models.ManyToManyField(blank=True, related_name='event_points', to='user.Progress', verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Балл мероприятий',
                'verbose_name_plural': 'Баллы мероприятий',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='pointsEvent',
            field=models.ManyToManyField(blank=True, related_name='participant', to='user.EventPoints', verbose_name='Баллы за мероприятия'),
        ),
    ]
