# Generated by Django 2.1.7 on 2019-05-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20190513_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_vk',
        ),
    ]
