# Generated by Django 2.1.7 on 2019-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_user_is_vk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_vk',
        ),
        migrations.AddField(
            model_name='user',
            name='is_social',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован через соц. сеть'),
        ),
    ]
