# Generated by Django 2.1.7 on 2019-03-04 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0016_auto_20190303_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryLink',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recoveryLink', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Ссылка на восстановление',
                'verbose_name_plural': 'Ссылки на восстановление',
            },
        ),
    ]
