# Generated by Django 2.1.7 on 2019-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverylink',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recoverylink',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
